CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT UNIQUE, password TEXT UNIQUE);
CREATE TABLE albums (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), name TEXT NOT NULL);
CREATE TABLE photos (id INTEGER PRIMARY KEY, album_id INTEGER REFERENCES albums(id), user_id INTEGER REFERENCES users(id), path TEXT UNIQUE);
CREATE TABLE album_permissions (album_id INTEGER REFERENCES albums(id), user_id INTEGER REFERENCES users(id));
CREATE TABLE sessions (user_id INTEGER REFERENCES users(id), session_id TEXT UNIQUE);
INSERT INTO users (email, password) VALUES ('u1@e.com', '$2a$10$TCRWGbqSjIeS7IXZ.L/PYefrGuQoIclp/OYwSRIORIa4137lEI/BC');
INSERT INTO albums (user_id, name) VALUES (1, '1 main');
INSERT INTO album_permissions (album_id, user_id) VALUES (1,1);
INSERT INTO photos (album_id, user_id, path) VALUES (1, 1, '/Users/ben/Documents/photoApp/Photos/1.jpg');
INSERT INTO photos (album_id, user_id, path) VALUES (1, 1, '/Users/ben/Documents/photoApp/Photos/2.png');